name: Deploy app to azure app services

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout src
        uses: actions/checkout@v3
      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: build project
        run: mvn clean install -DskipTests
      - name: upload artifact to deployment job
        uses: actions/upload-artifact@v2
        with:
          name: salomeMaterial
          path: ${{ github.workspace }}/target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: salomeMaterial
      - name: deploy to azure
        env:
          MAIL_PASSWORD_SENDER: ${{ secrets.MAIL_PASSWORD_SENDER }}
          MAIL_EMAIL_SENDER: ${{ secrets.MAIL_EMAIL_SENDER }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
        uses: azure/webapps-deploy@v2
        with:
          app-name: SalomeMaterial-api
          publish-profile: ${{ secrets.azureWebAppPublishProfile }}
          package: ${{ github.workspace }}/salomeMaterial/*.jar
